config/routes.rb
Lean::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  get "index" => "principal#index"
  get "donaciones" => "principal#donar"
  get "ayuda" => "principal#ayuda"

  get "persona" => "ganar#index"
  post "persona_guardar" => "ganar#guardar_miembro"
  post "visita_guardar" => "ganar#guardar_visita"
  post "persona_editar_miembro" => "ganar#editar_miembro"
  post "persona_editar_visita" => "ganar#editar_visita"
  post "persona_eliminar_persona" => "ganar#eliminar_persona"
  get "personacsv" => "ganar#personacsv"

  get "recuperar_persona_id/(:id)" => "ganar#recuperar_persona_id"
  get "recuperar_personas_inicio" => "ganar#recuperar_personas_inicio"
  get "recuperar_personas_filtrado/(:inicio)/(:fin)" => "ganar#recuperar_personas_filtro" , as: :recuperar_personas_filtro
  
  get "diezmos" => "diezmos#index"
  post "diezmos_guardar" => "diezmos#guardar"
  get "recuperar_diezmos_inicio" => "diezmos#recuperar_inicio"
  get "recuperar_diezmos_filtrado/(:inicio)/(:fin)" => "diezmos#recuperar_diezmo_filtro"

  get "ofrendas" => "ofrendas#index"
  post "ofrendas_guardar" => "ofrendas#guardar"
  get "recuperar_turno_inicio/(:id)" => "ofrendas#recuperar_turno", as: :recuperar_turnos
  get "recuperar_ofrendas_init" => "ofrendas#recuperar_init"
  get "recuperar_ofrendas_filtrado/(:inicio)/(:fin)" => "ofrendas#recuperar_ofrenda_filtro", as: :recuperar_ofrendas_filtro

  get "configuracion/servicios" => "configuracion#servicios"
  post "configuracion/guardar_servicio" => "configuracion#guardar_servicio"
  get "configuracion/recuperar_servicio" => "configuracion#recuperar_servicio"
  post "configuracion/editar_servicio" => "configuracion#editar_servicio"
  post "configuracion/drop_servicio" => "configuracion#drop_servicio"
  get "configuracion/get_dia_servicio/(:idservicio)" => "configuracion#get_dia_servicio"
  
  get "configuracion/usuario" => "configuracion#usuario"
  get "configuracion/recuperar_usuario" => "configuracion#recuperar_usuario"
  post "configuracion/guardar_usuario" => "configuracion#guardar_usuario"
  get "configuracion/recuperar_menu_usuario/(:id)" => "configuracion#recuperar_menu_usuario"
  post "configuracion/editar_usuario" => "configuracion#editar_usuario"

  get "configuracion/lugar" => "configuracion#lugar"
  get "configuracion/recuperar_lugar" => "configuracion#recuperar_lugar"
  post "configuracion/guardar_lugar" => "configuracion#guardar_lugar"
  post "configuracion/drop_lugar" => "configuracion#drop_lugar"
  post "configuracion/editar_lugar" => "configuracion#editar_lugar"

  get "configuracion/categoria" => "configuracion#categoria"
  post "configuracion/guardar_categoria" => "configuracion#guardar_categoria"
  get "configuracion/gettabla_categorias" => "configuracion#gettabla_categorias"
  post "configuracion/editar_categoria" => "configuracion#editar_categoria"

  get "configuracion/datos_generales" => "configuracion#datos_generales"
  get "configuracion/recuperar_datos_generales" => "configuracion#recuperar_datos_generales"
  post "configuracion/guardar_datos_generales" => "configuracion#guardar_datos_generales"
  get "persona_servicio_complete" => "serviciosgenerales#personas_autocomplete"
  get "getcategorias" => "serviciosgenerales#getcategorias"
  get "get_dia_servicio/(:idservicio)" => "serviciosgenerales#get_dia_servicio"

  get "asistencia" => "asistencia#index"
  post "asistencia_guardar" => "asistencia#guardar"
  get "recuperar_asistencia" => "asistencia#recuperar_asistencia"

  get "dashboard" => "informacion#index"
  get "data_miembro" => "informacion#chart_miembro"
  get "data_visitante" => "informacion#chart_visitante"
  get "data_pie" => "informacion#pie_chart_init"

  get "dashboard_diezmo" => "informacion#diezmo"
  post "recuperar_data_diezmo" => "informacion#recuperar_data_diezmo"
  get "dashboard_ofrenda" => "informacion#ofrenda"
  post "recuperar_data_ofrenda" => "informacion#recuperar_data_ofrenda"
  get "dashboard_membresia" => "informacion#membresia"
  get "dashboard_asistencia" => "informacion#asistencia"
  post "recuperar_data_asistencia" => "informacion#recuperar_data_asistencia"

  get "reporte_diezmo" => "reporte#diezmo"
  get "gettabladiezmo/(:inicio)/(:fin)/(:idpersona)" => "reporte#gettabladiezmo"
  get "diezmosexcel/(:inicio)/(:fin)/(:idpersona)/(:nombre)" => "reporte#diezmosexcel"
  get "reporte_ofrenda" => "reporte#ofrenda"
  get "gettablaofrenda/(:inicio)/(:fin)/(:idservicio)" => "reporte#gettablaofrenda"
  get "ofrendaesexcel/(:inicio)/(:fin)/(:idservicio)/(:nombre)" => "reporte#ofrendaesexcel"
  get "reporte_membresia" => "reporte#membresia"
  get "reporte_asistencia" => "reporte#asistencia"
  get "gettablaasistencia/(:inicio)/(:fin)" => "reporte#gettablaasistencia"
  get "gettablaasistenciageneral/(:inicio)/(:fin)" => "reporte#gettablaasistenciageneral"
  get "asistenciaexcel/(:inicio)/(:fin)/(:nombre)" => "reporte#asistenciaexcel"
  get "reporte_servicios" => "reporte#servicios"
  get "gettablamiembro/(:inicio)/(:fin)" => "reporte#gettablamiembro"
  get "miembrosexcel/(:inicio)/(:fin)/(:nombre)" => "reporte#miembrosexcel"
  get "gettablavisitante/(:inicio)/(:fin)" => "reporte#gettablavisitante"
  get "visitantesexcel/(:inicio)/(:fin)/(:nombre)" => "reporte#visitantesexcel"

  resources "sugerencias", only: [:new, :create]


  root 'principal#index'






  

end

app/models/asistencia.rb
class Asistencia < ActiveRecord::Base
	belongs_to :persona
	belongs_to :servicio
end

app/controllers/asistencia_controller.rb
require "date"
require "json"

class AsistenciaController < ApplicationController

	before_filter :authenticate_user!
	before_filter { |c| c.tiene_permiso "asistencia"}

	layout 'base'

	def index
		@titulo = 'Asistencia'
	end

	def guardar
		form = params[:formulario]
		tabla = params[:tabla]
		ActiveRecord::Base.transaction do
			begin
				servicio = Servicio.find(form[:servicio])
				tabla.each do |y|
					x = y.last
					asist = Asistencia.create(
						:dat_asistencia_fecregistro => DateTime.now(),
						:dat_asistencia_fecasistencia => form[:fecha],
						:int_asistencia_categoria => x[:categoriaid],
						:int_asistencia_cantidad => x[:asistente],
						:servicio => servicio
						)
				end
			rescue
				raise ActiveRecord::Rollback
			end
		end		
		render :json => {:data => tabla,:resp => "ok" } , :status => :ok
	end

	def recuperar_asistencia
		asistencia = ActiveRecord::Base.connection.execute("SELECT * from view_get_tbl_asistencia")
		render :json => { "aaData" => asistencia } , :status => :ok
	end

end

app/helpers/asistencia_helper.rb
module AsistenciaHelper
end

app/views/asistencia/index.html.haml
/ Dashboard wrapper start
.dashboard-wrapper
  / Page title start
  .row.page-title
    %h2
      Asistencia
      %small
        %li Home
        %li /
        %li Asistencia
  / Page title end
  / Row start
  .row
    #accordion.col-md-12
      .widget
        .widget-header
          %a#agregar.btn.btn-primary.btn-block
            Agregar Asistencia
        #regasistencia{style: "display:none"}
          .widget-body
            = form_tag(asistencia_guardar_path , {:method=>'post',:class=>'form-horizontal', :id => "form_asistencia", :name=> "form_asistencia"}) do
              .form-group
                %label.col-lg-2.control-label{for: "servicio"} Servicio
                .col-lg-2
                  = servicios_select()
              .form-group
                %label.col-lg-2.control-label{for: "fecha"} Fecha
                .col-lg-2
                  %input#fecha.form-control{name: "fecha", type: "text",class:"validate[required,custom[date]]"}/
              .form-group
                %label.col-lg-2.control-label{for: "categoria"} Categoría
                .col-lg-10
                  .row
                    .col-lg-3.col-sm-3
                      %select#categoria.form-control{name: "categoria"}
                    %label.col-lg-3.col-sm-3.control-label N° Asistentes
                    .col-lg-1.col-sm-1
                      %input#asistentes.form-control{name: "asistentes", type: "text", min:"0", class:"validate[custom[integer],min[0]]"}/
                    .col-lg-1.col-sm-1
                      %button#agregar_asistentes.btn.btn-default{"data-original-title" => "", type: "button"} +
              .dt_example.example_alt_pagination.col-lg-7.col-lg-offset-2
                %table#table_categoria_asistencia.table.table-condensed.table-striped.table-hover.table-bordered.pull-left
                  %thead
                    %tr
                      %th{style: "width:25%"} Servicio
                      %th{style: "width:25%"} Categoría
                      %th.hidden-phone{style: "width:25%"} Asistentes
                      %th.hidden-phone{style: "width:25%"} Acciones
                  %tbody

              .clearfix
              .form-group
                .col-lg-offset-2.col-lg-10
                  %button.cancelarGuardar.btn.btn-default{type: "button"} Cancelar
                  %input#btnGuardar_Asistencia.btn.btn-success{type: "button", value: "Guardar"}
  / Row end
  / Row start
  .row
    .col-md-12
      .widget
        .widget-header
          .title
            %span.fs1{"aria-hidden" => "true", "data-icon" => ""}
            Lista de Asistencia
        .widget-body
          .dt_example.example_alt_pagination
            %table#table_asistencia.data-table.table.table-condensed.table-striped.table-hover.table-bordered.pull-left
              %thead
                %tr
                  %th{style: "width:25%"} Servicio
                  %th{style: "width:35%"} Fecha
                  %th.hidden-phone{style: "width:15%"} Turno
                  %th.hidden-phone{style: "width:15%"} # asistencia
              %tbody
                
            .clearfix
  / Row end
  #loader{style: "display:none"}
    = render "layouts/loader"
/ Dashboard wrapper end
/ Main Container end
- content_for :bloquejavascript do
  = javascript_include_tag "wizard/bwizard.js"
  = javascript_include_tag :asistencia
  :javascript
    $('##{@mactive} > span').addClass('current-arrow');